import "../globals.css";
import { Providers } from "@/redux/provider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Login",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
