import "../globals.css";
import { Poppins, Inter } from "next/font/google";
import LayoutContext from "@/components/app/LayoutContext";
import { Providers } from "@/redux/provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "POS app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutContext>
          <Providers>{children}</Providers>
        </LayoutContext>
      </body>
    </html>
  );
}
