import "../../globals.css";
import { Jost } from "next/font/google";
import ReduxProvider from "@/redux/ReduxProvider";
import AuthLayout from "@/components/core/layouts/AuthLayout";

export const metadata = {
  title: "POS app auth",
  description: "Generated by create next app",
};

const jost = Jost({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={`${jost.className}`}>
        <ReduxProvider>
          <AuthLayout locale={locale}>{children}</AuthLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
