import Search from "./Search";

export const metadata = {
  title: "Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="md:p-6 bg-[#fafafa] min-h-screen">
      <Search />
      {children}
    </main>
  );
}
