import "./globals.css";
import { Poppins } from "next/font/google";
import LayoutContext from "@/components/app/LayoutContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "POS app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <LayoutContext>{children}</LayoutContext>
      </body>
    </html>
  );
}
