import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "POS app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-row justify-start">
        <Sidebar />
        <main className="bg-brand/20 flex-1 p-4">{children}</main>
      </body>
    </html>
  );
}
