"use client";

import TopBar from "@/components/app/TopBar";
import "./globals.css";
import { Poppins } from "next/font/google";
import { useState, useEffect, Fragment } from "react";
import { Transition } from "@headlessui/react";
import SideBar from "@/components/app/SideBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "POS app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showNav, setShowNav] = useState<boolean>(true);
  const [isMobile, setIsMobile] = useState<boolean>(false);

  function handleResize() {
    if (innerWidth <= 640) {
      setShowNav(false);
      setIsMobile(true);
    } else {
      setShowNav(true);
      setIsMobile(false);
    }
  }

  useEffect(() => {
    if (typeof window != undefined) {
      addEventListener("resize", handleResize);
    }

    return () => {
      removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <html lang="en">
      <body className={poppins.className}>
        <TopBar showNav={showNav} setShowNav={setShowNav} />
        <Transition
          as={Fragment}
          show={showNav}
          enter="transform transition duration-[400ms]"
          enterFrom="-translate-x-full"
          enterTo="translate-x-0"
          leave="transform duration-[400ms] transition ease-in-out"
          leaveFrom="translate-x-0"
          leaveTo="-translate-x-full"
        >
          <SideBar showNav={showNav} />
        </Transition>

        <main
          className={`h-screen pt-16 transition-all duration-[400ms] bg-white ${
            showNav && !isMobile ? "pl-56" : ""
          }`}
        >
          <div className="px-4 md:px-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
