import { Providers } from "@/redux/provider";
import "../globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Login",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
